//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("NLHModel", "FK_Employes_Departemets", "Departements", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Departements), "Employes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.Employes), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_Lits_Departemets", "Departements", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Departements), "Lits", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.Lits), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_Employes_Personnes", "Personnes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Personnes), "Employes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.Employes), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_FichierAdmission_Employes", "Employes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Employes), "FichierAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.FichierAdmission), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_FichierAdmission_Lits", "Lits", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Lits), "FichierAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.FichierAdmission), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_FichierAdmission_Patients", "Patients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Patients), "FichierAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.FichierAdmission), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.FichierAdmission), "FraisSupplemAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.FraisSupplemAdmission), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.FraisSupplementaires), "FraisSupplemAdmission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.FraisSupplemAdmission), true)]
[assembly: EdmRelationshipAttribute("NLHModel", "FK_Patients_Personnes", "Personnes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NLH_DLL.Personnes), "Patients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NLH_DLL.Patients), true)]

#endregion

namespace NLH_DLL
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class NLHEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet NLHEntities à l'aide de la chaîne de connexion trouvée dans la section 'NLHEntities' du fichier de configuration d'application.
        /// </summary>
        public NLHEntities() : base("name=NLHEntities", "NLHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet NLHEntities.
        /// </summary>
        public NLHEntities(string connectionString) : base(connectionString, "NLHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet NLHEntities.
        /// </summary>
        public NLHEntities(EntityConnection connection) : base(connection, "NLHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Departements> Departements
        {
            get
            {
                if ((_Departements == null))
                {
                    _Departements = base.CreateObjectSet<Departements>("Departements");
                }
                return _Departements;
            }
        }
        private ObjectSet<Departements> _Departements;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Employes> Employes
        {
            get
            {
                if ((_Employes == null))
                {
                    _Employes = base.CreateObjectSet<Employes>("Employes");
                }
                return _Employes;
            }
        }
        private ObjectSet<Employes> _Employes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FichierAdmission> FichierAdmission
        {
            get
            {
                if ((_FichierAdmission == null))
                {
                    _FichierAdmission = base.CreateObjectSet<FichierAdmission>("FichierAdmission");
                }
                return _FichierAdmission;
            }
        }
        private ObjectSet<FichierAdmission> _FichierAdmission;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FraisSupplemAdmission> FraisSupplemAdmission
        {
            get
            {
                if ((_FraisSupplemAdmission == null))
                {
                    _FraisSupplemAdmission = base.CreateObjectSet<FraisSupplemAdmission>("FraisSupplemAdmission");
                }
                return _FraisSupplemAdmission;
            }
        }
        private ObjectSet<FraisSupplemAdmission> _FraisSupplemAdmission;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FraisSupplementaires> FraisSupplementaires
        {
            get
            {
                if ((_FraisSupplementaires == null))
                {
                    _FraisSupplementaires = base.CreateObjectSet<FraisSupplementaires>("FraisSupplementaires");
                }
                return _FraisSupplementaires;
            }
        }
        private ObjectSet<FraisSupplementaires> _FraisSupplementaires;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Lits> Lits
        {
            get
            {
                if ((_Lits == null))
                {
                    _Lits = base.CreateObjectSet<Lits>("Lits");
                }
                return _Lits;
            }
        }
        private ObjectSet<Lits> _Lits;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Patients> Patients
        {
            get
            {
                if ((_Patients == null))
                {
                    _Patients = base.CreateObjectSet<Patients>("Patients");
                }
                return _Patients;
            }
        }
        private ObjectSet<Patients> _Patients;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Personnes> Personnes
        {
            get
            {
                if ((_Personnes == null))
                {
                    _Personnes = base.CreateObjectSet<Personnes>("Personnes");
                }
                return _Personnes;
            }
        }
        private ObjectSet<Personnes> _Personnes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Departements. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToDepartements(Departements departements)
        {
            base.AddObject("Departements", departements);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Employes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEmployes(Employes employes)
        {
            base.AddObject("Employes", employes);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FichierAdmission. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFichierAdmission(FichierAdmission fichierAdmission)
        {
            base.AddObject("FichierAdmission", fichierAdmission);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FraisSupplemAdmission. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFraisSupplemAdmission(FraisSupplemAdmission fraisSupplemAdmission)
        {
            base.AddObject("FraisSupplemAdmission", fraisSupplemAdmission);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FraisSupplementaires. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFraisSupplementaires(FraisSupplementaires fraisSupplementaires)
        {
            base.AddObject("FraisSupplementaires", fraisSupplementaires);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Lits. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToLits(Lits lits)
        {
            base.AddObject("Lits", lits);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Patients. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPatients(Patients patients)
        {
            base.AddObject("Patients", patients);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Personnes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToPersonnes(Personnes personnes)
        {
            base.AddObject("Personnes", personnes);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet sysdiagrams. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="Departements")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Departements : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Departements.
        /// </summary>
        /// <param name="iDDepartement">Valeur initiale de la propriété IDDepartement.</param>
        /// <param name="nomDepartement">Valeur initiale de la propriété NomDepartement.</param>
        public static Departements CreateDepartements(global::System.Int32 iDDepartement, global::System.String nomDepartement)
        {
            Departements departements = new Departements();
            departements.IDDepartement = iDDepartement;
            departements.NomDepartement = nomDepartement;
            return departements;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDDepartement
        {
            get
            {
                return _IDDepartement;
            }
            set
            {
                if (_IDDepartement != value)
                {
                    OnIDDepartementChanging(value);
                    ReportPropertyChanging("IDDepartement");
                    _IDDepartement = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDDepartement");
                    OnIDDepartementChanged();
                }
            }
        }
        private global::System.Int32 _IDDepartement;
        partial void OnIDDepartementChanging(global::System.Int32 value);
        partial void OnIDDepartementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomDepartement
        {
            get
            {
                return _NomDepartement;
            }
            set
            {
                OnNomDepartementChanging(value);
                ReportPropertyChanging("NomDepartement");
                _NomDepartement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomDepartement");
                OnNomDepartementChanged();
            }
        }
        private global::System.String _NomDepartement;
        partial void OnNomDepartementChanging(global::System.String value);
        partial void OnNomDepartementChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Employes_Departemets", "Employes")]
        public EntityCollection<Employes> Employes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employes>("NLHModel.FK_Employes_Departemets", "Employes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employes>("NLHModel.FK_Employes_Departemets", "Employes", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Lits_Departemets", "Lits")]
        public EntityCollection<Lits> Lits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lits>("NLHModel.FK_Lits_Departemets", "Lits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lits>("NLHModel.FK_Lits_Departemets", "Lits", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="Employes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employes : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Employes.
        /// </summary>
        /// <param name="iDEmploye">Valeur initiale de la propriété IDEmploye.</param>
        /// <param name="iDPersonne">Valeur initiale de la propriété IDPersonne.</param>
        /// <param name="iDDepartement">Valeur initiale de la propriété IDDepartement.</param>
        /// <param name="assuranceSocial">Valeur initiale de la propriété AssuranceSocial.</param>
        /// <param name="position">Valeur initiale de la propriété Position.</param>
        /// <param name="utilisateur">Valeur initiale de la propriété Utilisateur.</param>
        /// <param name="motdePasse">Valeur initiale de la propriété MotdePasse.</param>
        public static Employes CreateEmployes(global::System.Int32 iDEmploye, global::System.Int32 iDPersonne, global::System.Int32 iDDepartement, global::System.String assuranceSocial, global::System.String position, global::System.String utilisateur, global::System.String motdePasse)
        {
            Employes employes = new Employes();
            employes.IDEmploye = iDEmploye;
            employes.IDPersonne = iDPersonne;
            employes.IDDepartement = iDDepartement;
            employes.AssuranceSocial = assuranceSocial;
            employes.Position = position;
            employes.Utilisateur = utilisateur;
            employes.MotdePasse = motdePasse;
            return employes;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDEmploye
        {
            get
            {
                return _IDEmploye;
            }
            set
            {
                if (_IDEmploye != value)
                {
                    OnIDEmployeChanging(value);
                    ReportPropertyChanging("IDEmploye");
                    _IDEmploye = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDEmploye");
                    OnIDEmployeChanged();
                }
            }
        }
        private global::System.Int32 _IDEmploye;
        partial void OnIDEmployeChanging(global::System.Int32 value);
        partial void OnIDEmployeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPersonne
        {
            get
            {
                return _IDPersonne;
            }
            set
            {
                OnIDPersonneChanging(value);
                ReportPropertyChanging("IDPersonne");
                _IDPersonne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPersonne");
                OnIDPersonneChanged();
            }
        }
        private global::System.Int32 _IDPersonne;
        partial void OnIDPersonneChanging(global::System.Int32 value);
        partial void OnIDPersonneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDDepartement
        {
            get
            {
                return _IDDepartement;
            }
            set
            {
                OnIDDepartementChanging(value);
                ReportPropertyChanging("IDDepartement");
                _IDDepartement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDDepartement");
                OnIDDepartementChanged();
            }
        }
        private global::System.Int32 _IDDepartement;
        partial void OnIDDepartementChanging(global::System.Int32 value);
        partial void OnIDDepartementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssuranceSocial
        {
            get
            {
                return _AssuranceSocial;
            }
            set
            {
                OnAssuranceSocialChanging(value);
                ReportPropertyChanging("AssuranceSocial");
                _AssuranceSocial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssuranceSocial");
                OnAssuranceSocialChanged();
            }
        }
        private global::System.String _AssuranceSocial;
        partial void OnAssuranceSocialChanging(global::System.String value);
        partial void OnAssuranceSocialChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Utilisateur
        {
            get
            {
                return _Utilisateur;
            }
            set
            {
                OnUtilisateurChanging(value);
                ReportPropertyChanging("Utilisateur");
                _Utilisateur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Utilisateur");
                OnUtilisateurChanged();
            }
        }
        private global::System.String _Utilisateur;
        partial void OnUtilisateurChanging(global::System.String value);
        partial void OnUtilisateurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MotdePasse
        {
            get
            {
                return _MotdePasse;
            }
            set
            {
                OnMotdePasseChanging(value);
                ReportPropertyChanging("MotdePasse");
                _MotdePasse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MotdePasse");
                OnMotdePasseChanged();
            }
        }
        private global::System.String _MotdePasse;
        partial void OnMotdePasseChanging(global::System.String value);
        partial void OnMotdePasseChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Employes_Departemets", "Departements")]
        public Departements Departements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Employes_Departemets", "Departements").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Employes_Departemets", "Departements").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Departements> DepartementsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Employes_Departemets", "Departements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Departements>("NLHModel.FK_Employes_Departemets", "Departements", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Employes_Personnes", "Personnes")]
        public Personnes Personnes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Employes_Personnes", "Personnes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Employes_Personnes", "Personnes").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Personnes> PersonnesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Employes_Personnes", "Personnes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Personnes>("NLHModel.FK_Employes_Personnes", "Personnes", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Employes", "FichierAdmission")]
        public EntityCollection<FichierAdmission> FichierAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Employes", "FichierAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Employes", "FichierAdmission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="FichierAdmission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FichierAdmission : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FichierAdmission.
        /// </summary>
        /// <param name="iDAdmission">Valeur initiale de la propriété IDAdmission.</param>
        /// <param name="iDPatient">Valeur initiale de la propriété IDPatient.</param>
        /// <param name="iDEmploye">Valeur initiale de la propriété IDEmploye.</param>
        /// <param name="iDLit">Valeur initiale de la propriété IDLit.</param>
        /// <param name="dateAdmission">Valeur initiale de la propriété DateAdmission.</param>
        /// <param name="assurancePrivee">Valeur initiale de la propriété AssurancePrivee.</param>
        public static FichierAdmission CreateFichierAdmission(global::System.Int32 iDAdmission, global::System.Int32 iDPatient, global::System.Int32 iDEmploye, global::System.Int32 iDLit, global::System.DateTime dateAdmission, global::System.String assurancePrivee)
        {
            FichierAdmission fichierAdmission = new FichierAdmission();
            fichierAdmission.IDAdmission = iDAdmission;
            fichierAdmission.IDPatient = iDPatient;
            fichierAdmission.IDEmploye = iDEmploye;
            fichierAdmission.IDLit = iDLit;
            fichierAdmission.DateAdmission = dateAdmission;
            fichierAdmission.AssurancePrivee = assurancePrivee;
            return fichierAdmission;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAdmission
        {
            get
            {
                return _IDAdmission;
            }
            set
            {
                if (_IDAdmission != value)
                {
                    OnIDAdmissionChanging(value);
                    ReportPropertyChanging("IDAdmission");
                    _IDAdmission = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDAdmission");
                    OnIDAdmissionChanged();
                }
            }
        }
        private global::System.Int32 _IDAdmission;
        partial void OnIDAdmissionChanging(global::System.Int32 value);
        partial void OnIDAdmissionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPatient
        {
            get
            {
                return _IDPatient;
            }
            set
            {
                OnIDPatientChanging(value);
                ReportPropertyChanging("IDPatient");
                _IDPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPatient");
                OnIDPatientChanged();
            }
        }
        private global::System.Int32 _IDPatient;
        partial void OnIDPatientChanging(global::System.Int32 value);
        partial void OnIDPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDEmploye
        {
            get
            {
                return _IDEmploye;
            }
            set
            {
                OnIDEmployeChanging(value);
                ReportPropertyChanging("IDEmploye");
                _IDEmploye = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDEmploye");
                OnIDEmployeChanged();
            }
        }
        private global::System.Int32 _IDEmploye;
        partial void OnIDEmployeChanging(global::System.Int32 value);
        partial void OnIDEmployeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDLit
        {
            get
            {
                return _IDLit;
            }
            set
            {
                OnIDLitChanging(value);
                ReportPropertyChanging("IDLit");
                _IDLit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDLit");
                OnIDLitChanged();
            }
        }
        private global::System.Int32 _IDLit;
        partial void OnIDLitChanging(global::System.Int32 value);
        partial void OnIDLitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdmission
        {
            get
            {
                return _DateAdmission;
            }
            set
            {
                OnDateAdmissionChanging(value);
                ReportPropertyChanging("DateAdmission");
                _DateAdmission = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdmission");
                OnDateAdmissionChanged();
            }
        }
        private global::System.DateTime _DateAdmission;
        partial void OnDateAdmissionChanging(global::System.DateTime value);
        partial void OnDateAdmissionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateConge
        {
            get
            {
                return _DateConge;
            }
            set
            {
                OnDateCongeChanging(value);
                ReportPropertyChanging("DateConge");
                _DateConge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateConge");
                OnDateCongeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateConge;
        partial void OnDateCongeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCongeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssurancePrivee
        {
            get
            {
                return _AssurancePrivee;
            }
            set
            {
                OnAssurancePriveeChanging(value);
                ReportPropertyChanging("AssurancePrivee");
                _AssurancePrivee = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssurancePrivee");
                OnAssurancePriveeChanged();
            }
        }
        private global::System.String _AssurancePrivee;
        partial void OnAssurancePriveeChanging(global::System.String value);
        partial void OnAssurancePriveeChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Employes", "Employes")]
        public Employes Employes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employes>("NLHModel.FK_FichierAdmission_Employes", "Employes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employes>("NLHModel.FK_FichierAdmission_Employes", "Employes").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employes> EmployesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employes>("NLHModel.FK_FichierAdmission_Employes", "Employes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employes>("NLHModel.FK_FichierAdmission_Employes", "Employes", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Lits", "Lits")]
        public Lits Lits
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("NLHModel.FK_FichierAdmission_Lits", "Lits").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("NLHModel.FK_FichierAdmission_Lits", "Lits").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lits> LitsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lits>("NLHModel.FK_FichierAdmission_Lits", "Lits");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lits>("NLHModel.FK_FichierAdmission_Lits", "Lits", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Patients", "Patients")]
        public Patients Patients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patients>("NLHModel.FK_FichierAdmission_Patients", "Patients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patients>("NLHModel.FK_FichierAdmission_Patients", "Patients").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Patients> PatientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Patients>("NLHModel.FK_FichierAdmission_Patients", "Patients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Patients>("NLHModel.FK_FichierAdmission_Patients", "Patients", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FraisSupplemAdmission_FichierAdmission", "FraisSupplemAdmission")]
        public EntityCollection<FraisSupplemAdmission> FraisSupplemAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FraisSupplemAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FraisSupplemAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FraisSupplemAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FraisSupplemAdmission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="FraisSupplemAdmission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FraisSupplemAdmission : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FraisSupplemAdmission.
        /// </summary>
        /// <param name="iDFraisAdminission">Valeur initiale de la propriété IDFraisAdminission.</param>
        /// <param name="iDAdmission">Valeur initiale de la propriété IDAdmission.</param>
        /// <param name="iDFraisSupplementaires">Valeur initiale de la propriété IDFraisSupplementaires.</param>
        public static FraisSupplemAdmission CreateFraisSupplemAdmission(global::System.Int32 iDFraisAdminission, global::System.Int32 iDAdmission, global::System.Int32 iDFraisSupplementaires)
        {
            FraisSupplemAdmission fraisSupplemAdmission = new FraisSupplemAdmission();
            fraisSupplemAdmission.IDFraisAdminission = iDFraisAdminission;
            fraisSupplemAdmission.IDAdmission = iDAdmission;
            fraisSupplemAdmission.IDFraisSupplementaires = iDFraisSupplementaires;
            return fraisSupplemAdmission;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFraisAdminission
        {
            get
            {
                return _IDFraisAdminission;
            }
            set
            {
                if (_IDFraisAdminission != value)
                {
                    OnIDFraisAdminissionChanging(value);
                    ReportPropertyChanging("IDFraisAdminission");
                    _IDFraisAdminission = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFraisAdminission");
                    OnIDFraisAdminissionChanged();
                }
            }
        }
        private global::System.Int32 _IDFraisAdminission;
        partial void OnIDFraisAdminissionChanging(global::System.Int32 value);
        partial void OnIDFraisAdminissionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDAdmission
        {
            get
            {
                return _IDAdmission;
            }
            set
            {
                OnIDAdmissionChanging(value);
                ReportPropertyChanging("IDAdmission");
                _IDAdmission = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDAdmission");
                OnIDAdmissionChanged();
            }
        }
        private global::System.Int32 _IDAdmission;
        partial void OnIDAdmissionChanging(global::System.Int32 value);
        partial void OnIDAdmissionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFraisSupplementaires
        {
            get
            {
                return _IDFraisSupplementaires;
            }
            set
            {
                OnIDFraisSupplementairesChanging(value);
                ReportPropertyChanging("IDFraisSupplementaires");
                _IDFraisSupplementaires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDFraisSupplementaires");
                OnIDFraisSupplementairesChanged();
            }
        }
        private global::System.Int32 _IDFraisSupplementaires;
        partial void OnIDFraisSupplementairesChanging(global::System.Int32 value);
        partial void OnIDFraisSupplementairesChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission")]
        public FichierAdmission FichierAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FichierAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FichierAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FichierAdmission> FichierAdmissionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FichierAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FichierAdmission>("NLHModel.FK_FraisSupplemAdmission_FichierAdmission", "FichierAdmission", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires")]
        public FraisSupplementaires FraisSupplementaires
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FraisSupplementaires>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FraisSupplementaires>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FraisSupplementaires> FraisSupplementairesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FraisSupplementaires>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FraisSupplementaires>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplementaires", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="FraisSupplementaires")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FraisSupplementaires : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FraisSupplementaires.
        /// </summary>
        /// <param name="iDFraisSupplementaires">Valeur initiale de la propriété IDFraisSupplementaires.</param>
        /// <param name="fraisTelephone">Valeur initiale de la propriété FraisTelephone.</param>
        /// <param name="fraisTV">Valeur initiale de la propriété FraisTV.</param>
        /// <param name="fraisLitSemiPrivee">Valeur initiale de la propriété FraisLitSemiPrivee.</param>
        /// <param name="fraisLitPrivee">Valeur initiale de la propriété FraisLitPrivee.</param>
        public static FraisSupplementaires CreateFraisSupplementaires(global::System.Int32 iDFraisSupplementaires, global::System.Single fraisTelephone, global::System.Single fraisTV, global::System.Single fraisLitSemiPrivee, global::System.Single fraisLitPrivee)
        {
            FraisSupplementaires fraisSupplementaires = new FraisSupplementaires();
            fraisSupplementaires.IDFraisSupplementaires = iDFraisSupplementaires;
            fraisSupplementaires.FraisTelephone = fraisTelephone;
            fraisSupplementaires.FraisTV = fraisTV;
            fraisSupplementaires.FraisLitSemiPrivee = fraisLitSemiPrivee;
            fraisSupplementaires.FraisLitPrivee = fraisLitPrivee;
            return fraisSupplementaires;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDFraisSupplementaires
        {
            get
            {
                return _IDFraisSupplementaires;
            }
            set
            {
                if (_IDFraisSupplementaires != value)
                {
                    OnIDFraisSupplementairesChanging(value);
                    ReportPropertyChanging("IDFraisSupplementaires");
                    _IDFraisSupplementaires = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDFraisSupplementaires");
                    OnIDFraisSupplementairesChanged();
                }
            }
        }
        private global::System.Int32 _IDFraisSupplementaires;
        partial void OnIDFraisSupplementairesChanging(global::System.Int32 value);
        partial void OnIDFraisSupplementairesChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single FraisTelephone
        {
            get
            {
                return _FraisTelephone;
            }
            set
            {
                OnFraisTelephoneChanging(value);
                ReportPropertyChanging("FraisTelephone");
                _FraisTelephone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FraisTelephone");
                OnFraisTelephoneChanged();
            }
        }
        private global::System.Single _FraisTelephone;
        partial void OnFraisTelephoneChanging(global::System.Single value);
        partial void OnFraisTelephoneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single FraisTV
        {
            get
            {
                return _FraisTV;
            }
            set
            {
                OnFraisTVChanging(value);
                ReportPropertyChanging("FraisTV");
                _FraisTV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FraisTV");
                OnFraisTVChanged();
            }
        }
        private global::System.Single _FraisTV;
        partial void OnFraisTVChanging(global::System.Single value);
        partial void OnFraisTVChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single FraisLitSemiPrivee
        {
            get
            {
                return _FraisLitSemiPrivee;
            }
            set
            {
                OnFraisLitSemiPriveeChanging(value);
                ReportPropertyChanging("FraisLitSemiPrivee");
                _FraisLitSemiPrivee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FraisLitSemiPrivee");
                OnFraisLitSemiPriveeChanged();
            }
        }
        private global::System.Single _FraisLitSemiPrivee;
        partial void OnFraisLitSemiPriveeChanging(global::System.Single value);
        partial void OnFraisLitSemiPriveeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single FraisLitPrivee
        {
            get
            {
                return _FraisLitPrivee;
            }
            set
            {
                OnFraisLitPriveeChanging(value);
                ReportPropertyChanging("FraisLitPrivee");
                _FraisLitPrivee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FraisLitPrivee");
                OnFraisLitPriveeChanged();
            }
        }
        private global::System.Single _FraisLitPrivee;
        partial void OnFraisLitPriveeChanging(global::System.Single value);
        partial void OnFraisLitPriveeChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplemAdmission")]
        public EntityCollection<FraisSupplemAdmission> FraisSupplemAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FraisSupplemAdmission>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplemAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FraisSupplemAdmission>("NLHModel.FK_FraisSupplemAdmission_FraisSupplementaires", "FraisSupplemAdmission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="Lits")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lits : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Lits.
        /// </summary>
        /// <param name="iDLits">Valeur initiale de la propriété IDLits.</param>
        /// <param name="iDDepartement">Valeur initiale de la propriété IDDepartement.</param>
        /// <param name="description">Valeur initiale de la propriété Description.</param>
        public static Lits CreateLits(global::System.Int32 iDLits, global::System.Int32 iDDepartement, global::System.String description)
        {
            Lits lits = new Lits();
            lits.IDLits = iDLits;
            lits.IDDepartement = iDDepartement;
            lits.Description = description;
            return lits;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDLits
        {
            get
            {
                return _IDLits;
            }
            set
            {
                if (_IDLits != value)
                {
                    OnIDLitsChanging(value);
                    ReportPropertyChanging("IDLits");
                    _IDLits = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDLits");
                    OnIDLitsChanged();
                }
            }
        }
        private global::System.Int32 _IDLits;
        partial void OnIDLitsChanging(global::System.Int32 value);
        partial void OnIDLitsChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDDepartement
        {
            get
            {
                return _IDDepartement;
            }
            set
            {
                OnIDDepartementChanging(value);
                ReportPropertyChanging("IDDepartement");
                _IDDepartement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDDepartement");
                OnIDDepartementChanged();
            }
        }
        private global::System.Int32 _IDDepartement;
        partial void OnIDDepartementChanging(global::System.Int32 value);
        partial void OnIDDepartementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeLit
        {
            get
            {
                return _TypeLit;
            }
            set
            {
                OnTypeLitChanging(value);
                ReportPropertyChanging("TypeLit");
                _TypeLit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypeLit");
                OnTypeLitChanged();
            }
        }
        private global::System.String _TypeLit;
        partial void OnTypeLitChanging(global::System.String value);
        partial void OnTypeLitChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Lits_Departemets", "Departements")]
        public Departements Departements
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Lits_Departemets", "Departements").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Lits_Departemets", "Departements").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Departements> DepartementsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Departements>("NLHModel.FK_Lits_Departemets", "Departements");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Departements>("NLHModel.FK_Lits_Departemets", "Departements", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Lits", "FichierAdmission")]
        public EntityCollection<FichierAdmission> FichierAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Lits", "FichierAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Lits", "FichierAdmission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="Patients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patients : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Patients.
        /// </summary>
        /// <param name="iDPatient">Valeur initiale de la propriété IDPatient.</param>
        /// <param name="iDPersonne">Valeur initiale de la propriété IDPersonne.</param>
        /// <param name="parentPlusProche">Valeur initiale de la propriété ParentPlusProche.</param>
        public static Patients CreatePatients(global::System.Int32 iDPatient, global::System.Int32 iDPersonne, global::System.String parentPlusProche)
        {
            Patients patients = new Patients();
            patients.IDPatient = iDPatient;
            patients.IDPersonne = iDPersonne;
            patients.ParentPlusProche = parentPlusProche;
            return patients;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPatient
        {
            get
            {
                return _IDPatient;
            }
            set
            {
                if (_IDPatient != value)
                {
                    OnIDPatientChanging(value);
                    ReportPropertyChanging("IDPatient");
                    _IDPatient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPatient");
                    OnIDPatientChanged();
                }
            }
        }
        private global::System.Int32 _IDPatient;
        partial void OnIDPatientChanging(global::System.Int32 value);
        partial void OnIDPatientChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPersonne
        {
            get
            {
                return _IDPersonne;
            }
            set
            {
                OnIDPersonneChanging(value);
                ReportPropertyChanging("IDPersonne");
                _IDPersonne = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDPersonne");
                OnIDPersonneChanged();
            }
        }
        private global::System.Int32 _IDPersonne;
        partial void OnIDPersonneChanging(global::System.Int32 value);
        partial void OnIDPersonneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentPlusProche
        {
            get
            {
                return _ParentPlusProche;
            }
            set
            {
                OnParentPlusProcheChanging(value);
                ReportPropertyChanging("ParentPlusProche");
                _ParentPlusProche = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParentPlusProche");
                OnParentPlusProcheChanged();
            }
        }
        private global::System.String _ParentPlusProche;
        partial void OnParentPlusProcheChanging(global::System.String value);
        partial void OnParentPlusProcheChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_FichierAdmission_Patients", "FichierAdmission")]
        public EntityCollection<FichierAdmission> FichierAdmission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Patients", "FichierAdmission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FichierAdmission>("NLHModel.FK_FichierAdmission_Patients", "FichierAdmission", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Patients_Personnes", "Personnes")]
        public Personnes Personnes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Patients_Personnes", "Personnes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Patients_Personnes", "Personnes").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Personnes> PersonnesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Personnes>("NLHModel.FK_Patients_Personnes", "Personnes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Personnes>("NLHModel.FK_Patients_Personnes", "Personnes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="Personnes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Personnes : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Personnes.
        /// </summary>
        /// <param name="iDPersonne">Valeur initiale de la propriété IDPersonne.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="nomFamille">Valeur initiale de la propriété NomFamille.</param>
        /// <param name="adresse">Valeur initiale de la propriété Adresse.</param>
        /// <param name="ville">Valeur initiale de la propriété Ville.</param>
        /// <param name="province">Valeur initiale de la propriété Province.</param>
        /// <param name="codePostal">Valeur initiale de la propriété CodePostal.</param>
        /// <param name="telephonePrinc">Valeur initiale de la propriété TelephonePrinc.</param>
        /// <param name="dateNaissance">Valeur initiale de la propriété DateNaissance.</param>
        /// <param name="sexe">Valeur initiale de la propriété Sexe.</param>
        /// <param name="assuranceMaladie">Valeur initiale de la propriété AssuranceMaladie.</param>
        public static Personnes CreatePersonnes(global::System.Int32 iDPersonne, global::System.String prenom, global::System.String nomFamille, global::System.String adresse, global::System.String ville, global::System.String province, global::System.String codePostal, global::System.String telephonePrinc, global::System.DateTime dateNaissance, global::System.String sexe, global::System.String assuranceMaladie)
        {
            Personnes personnes = new Personnes();
            personnes.IDPersonne = iDPersonne;
            personnes.Prenom = prenom;
            personnes.NomFamille = nomFamille;
            personnes.Adresse = adresse;
            personnes.Ville = ville;
            personnes.Province = province;
            personnes.CodePostal = codePostal;
            personnes.TelephonePrinc = telephonePrinc;
            personnes.DateNaissance = dateNaissance;
            personnes.Sexe = sexe;
            personnes.AssuranceMaladie = assuranceMaladie;
            return personnes;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDPersonne
        {
            get
            {
                return _IDPersonne;
            }
            set
            {
                if (_IDPersonne != value)
                {
                    OnIDPersonneChanging(value);
                    ReportPropertyChanging("IDPersonne");
                    _IDPersonne = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPersonne");
                    OnIDPersonneChanged();
                }
            }
        }
        private global::System.Int32 _IDPersonne;
        partial void OnIDPersonneChanging(global::System.Int32 value);
        partial void OnIDPersonneChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomFamille
        {
            get
            {
                return _NomFamille;
            }
            set
            {
                OnNomFamilleChanging(value);
                ReportPropertyChanging("NomFamille");
                _NomFamille = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomFamille");
                OnNomFamilleChanged();
            }
        }
        private global::System.String _NomFamille;
        partial void OnNomFamilleChanging(global::System.String value);
        partial void OnNomFamilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ville
        {
            get
            {
                return _Ville;
            }
            set
            {
                OnVilleChanging(value);
                ReportPropertyChanging("Ville");
                _Ville = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ville");
                OnVilleChanged();
            }
        }
        private global::System.String _Ville;
        partial void OnVilleChanging(global::System.String value);
        partial void OnVilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodePostal
        {
            get
            {
                return _CodePostal;
            }
            set
            {
                OnCodePostalChanging(value);
                ReportPropertyChanging("CodePostal");
                _CodePostal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodePostal");
                OnCodePostalChanged();
            }
        }
        private global::System.String _CodePostal;
        partial void OnCodePostalChanging(global::System.String value);
        partial void OnCodePostalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TelephonePrinc
        {
            get
            {
                return _TelephonePrinc;
            }
            set
            {
                OnTelephonePrincChanging(value);
                ReportPropertyChanging("TelephonePrinc");
                _TelephonePrinc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelephonePrinc");
                OnTelephonePrincChanged();
            }
        }
        private global::System.String _TelephonePrinc;
        partial void OnTelephonePrincChanging(global::System.String value);
        partial void OnTelephonePrincChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneAutre
        {
            get
            {
                return _TelephoneAutre;
            }
            set
            {
                OnTelephoneAutreChanging(value);
                ReportPropertyChanging("TelephoneAutre");
                _TelephoneAutre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneAutre");
                OnTelephoneAutreChanged();
            }
        }
        private global::System.String _TelephoneAutre;
        partial void OnTelephoneAutreChanging(global::System.String value);
        partial void OnTelephoneAutreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateNaissance
        {
            get
            {
                return _DateNaissance;
            }
            set
            {
                OnDateNaissanceChanging(value);
                ReportPropertyChanging("DateNaissance");
                _DateNaissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateNaissance");
                OnDateNaissanceChanged();
            }
        }
        private global::System.DateTime _DateNaissance;
        partial void OnDateNaissanceChanging(global::System.DateTime value);
        partial void OnDateNaissanceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexe
        {
            get
            {
                return _Sexe;
            }
            set
            {
                OnSexeChanging(value);
                ReportPropertyChanging("Sexe");
                _Sexe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sexe");
                OnSexeChanged();
            }
        }
        private global::System.String _Sexe;
        partial void OnSexeChanging(global::System.String value);
        partial void OnSexeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssuranceMaladie
        {
            get
            {
                return _AssuranceMaladie;
            }
            set
            {
                OnAssuranceMaladieChanging(value);
                ReportPropertyChanging("AssuranceMaladie");
                _AssuranceMaladie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssuranceMaladie");
                OnAssuranceMaladieChanged();
            }
        }
        private global::System.String _AssuranceMaladie;
        partial void OnAssuranceMaladieChanging(global::System.String value);
        partial void OnAssuranceMaladieChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Employes_Personnes", "Employes")]
        public EntityCollection<Employes> Employes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employes>("NLHModel.FK_Employes_Personnes", "Employes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employes>("NLHModel.FK_Employes_Personnes", "Employes", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NLHModel", "FK_Patients_Personnes", "Patients")]
        public EntityCollection<Patients> Patients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Patients>("NLHModel.FK_Patients_Personnes", "Patients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Patients>("NLHModel.FK_Patients_Personnes", "Patients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NLHModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet sysdiagrams.
        /// </summary>
        /// <param name="name">Valeur initiale de la propriété name.</param>
        /// <param name="principal_id">Valeur initiale de la propriété principal_id.</param>
        /// <param name="diagram_id">Valeur initiale de la propriété diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
